#!/usr/bin/make -f

default:
	@echo "Please choose a target to build"

install:
	npm install

build:
	npm run build

dev:
	npm run start

lint:
	npm run lint

format:
	npm run format

test:
	npm run test

coverage:
	npm run coverage

.PHONY: default install build dev lint format test coverage
