repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.2.2
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]

  - repo: https://github.com/sourcery-ai/sourcery
    rev: v1.3.0
    hooks:
      - id: sourcery
        args: [--diff=git diff HEAD, --no-summary]
        files: backend/

  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: make backend isort
        types: [python]
        files: backend/

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: make backend black
        types: [python]
        files: backend/

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: make backend flake8
        types: [python]
        exclude: setup.py
        files: backend/

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: make backend mypy
        types: [python]
        pass_filenames: false
        files: backend/

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: make backend test
        types: [python]
        files: backend/
