repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.2.2
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]

  - repo: https://github.com/sourcery-ai/sourcery
    rev: v1.3.0
    hooks:
      - id: sourcery
        args: [--diff=git diff HEAD, --no-summary]
        files: backend/

  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: env PIPENV_PIPFILE=backend/Pipfile pipenv run isort
        args: ["--settings-path=backend/setup.cfg"]
        types: [python]
        files: backend/

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: env PIPENV_PIPFILE=backend/Pipfile pipenv run black
        types: [python]
        files: backend/

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: env PIPENV_PIPFILE=backend/Pipfile pipenv run flake8
        args: ["--config=backend/setup.cfg"]
        types: [python]
        exclude: setup.py
        files: backend/

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: env PIPENV_PIPFILE=backend/Pipfile pipenv run mypy
        args: ["--config-file=backend/setup.cfg"]
        types: [python]
        pass_filenames: false
        files: backend/

      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: env PIPENV_PIPFILE=backend/Pipfile pipenv run pytest
        args: ["--cov=app", "--cov-report", "term-missing", "--cov-branch", "--cov-report", "term"]
        types: [python]
        files: backend/
