name: Setup frontend
description: Setup development environment for frontend

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: '>=16'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      shell: bash
      run: |
        cd frontend
        npm ci
