# Generated by Django 4.2.2 on 2023-06-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extra", "0002_chatconversationcontext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatconversationcontext",
            name="context",
            field=models.JSONField(default=dict),
        ),
    ]
