# Generated by Django 4.2.1 on 2023-06-03 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("name", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("rating", models.DecimalField(decimal_places=2, max_digits=7)),
                ("numReviews", models.IntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                ("countInStock", models.IntegerField(default=0)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
