# Generated by Django 4.2.1 on 2023-06-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_order_shippingaddress_review_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/placeholder.png", null=True, upload_to=""
            ),
        ),
    ]
