name: Setup backend
description: Setup development environment for backend

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pipenv'

    - name: Install pipenv
      shell: bash
      run: |
        cd backend
        python -m pip install --upgrade pipenv wheel

    - name: Install dependencies
      shell: bash
      run: |
        cd backend
        pipenv install --deploy --dev
