# Generated by Django 4.2.1 on 2023-06-04 14:11

from django.db import migrations

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_username_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
