# Generated by Django 4.2.2 on 2023-06-08 13:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_remove_order_paymentmethod_remove_orderitem_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="qty",
            new_name="quantity",
        ),
    ]
