# Generated by Django 4.2.2 on 2023-06-08 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_order_shippingprice_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
