# Generated by Django 4.2.2 on 2023-06-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_order_invoiceid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="invoiceId",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="paymentIntentId",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
    ]
