name: Frontend CI

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup frontend
        uses: ./.github/actions/setup-frontend

      - name: Lint
        run: make frontend lint

      - name: Test
        run: make frontend coverage

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: frontend/docs/coverage-final.json
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md
