name: Frontend CI

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup frontend
        uses: ./.github/actions/setup-frontend

      - name: Lint
        run: make frontend lint

      - name: Test
        run: make frontend coverage
        env:
          CI: true

      - name: Code coverage report
        if: always()
        uses: davelosert/vitest-coverage-report-action@v1
        with:
          working-directory: frontend/
          github-token: ${{ secrets.GITHUB_TOKEN }}
